// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic type structure
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          name: string | null
          age: number | null
          photo: string | null
          phone: string | null
          email: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name?: string | null
          age?: number | null
          photo?: string | null
          phone?: string | null
          email?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          age?: number | null
          photo?: string | null
          phone?: string | null
          email?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      venues: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          address: string
          city: string
          pincode: string | null
          coordinates: string | null
          phone: string | null
          email: string | null
          status: "pending" | "approved" | "rejected"
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          address: string
          city: string
          pincode?: string | null
          coordinates?: string | null
          phone?: string | null
          email?: string | null
          status?: "pending" | "approved" | "rejected"
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          address?: string
          city?: string
          pincode?: string | null
          coordinates?: string | null
          phone?: string | null
          email?: string | null
          status?: "pending" | "approved" | "rejected"
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          venue_id: string
          name: string
          description: string | null
          date: string
          time: string
          genre: string
          price: number
          capacity: number
          booked: number
          dress_code: string | null
          images: string[] | null
          rating: number
          location: Json | null
          rules: string[] | null
          amenities: string[] | null
          contact: Json | null
          category_ratings: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          venue_id: string
          name: string
          description?: string | null
          date: string
          time: string
          genre: string
          price: number
          capacity: number
          booked?: number
          dress_code?: string | null
          images?: string[] | null
          rating?: number
          location?: Json | null
          rules?: string[] | null
          amenities?: string[] | null
          contact?: Json | null
          category_ratings?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          venue_id?: string
          name?: string
          description?: string | null
          date?: string
          time?: string
          genre?: string
          price?: number
          capacity?: number
          booked?: number
          dress_code?: string | null
          images?: string[] | null
          rating?: number
          location?: Json | null
          rules?: string[] | null
          amenities?: string[] | null
          contact?: Json | null
          category_ratings?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      bookings: {
        Row: {
          id: string
          user_id: string
          event_id: string
          number_of_people: number
          price_per_person: number
          total_price: number
          status: "confirmed" | "cancelled" | "refunded"
          qr_code: string | null
          payment_id: string | null
          payment_status: "pending" | "completed" | "failed" | "refunded"
          booking_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          user_id: string
          event_id: string
          number_of_people: number
          price_per_person: number
          total_price: number
          status?: "confirmed" | "cancelled" | "refunded"
          qr_code?: string | null
          payment_id?: string | null
          payment_status?: "pending" | "completed" | "failed" | "refunded"
          booking_date?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event_id?: string
          number_of_people?: number
          price_per_person?: number
          total_price?: number
          status?: "confirmed" | "cancelled" | "refunded"
          qr_code?: string | null
          payment_id?: string | null
          payment_status?: "pending" | "completed" | "failed" | "refunded"
          booking_date?: string
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          user_id: string
          event_id: string
          rating: number
          comment: string | null
          helpful_count: number
          category_ratings: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event_id: string
          rating: number
          comment?: string | null
          helpful_count?: number
          category_ratings?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          event_id?: string
          rating?: number
          comment?: string | null
          helpful_count?: number
          category_ratings?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

